### ISSUE TITLE
Euca 5 FastStart failure on CentOS 7.9

### ISSUE THREAD

**Issue by ndtroubleshoot** [Corymbia/eucalyptus-ansible#13]
I just tried the Euca 5 FastStart ansible install on a pristine CentOS 7.9 minimal install server.  The installation log file shows this one failure in the ansible playbook:

TASK [ceph-common : firewalld cluster interface zone] **************************
fatal: [host1]: FAILED! => {"changed": false, "msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: INVALID_INTERFACE Permanent and Non-Permanent(immediate) operation"}

PLAY RECAP *********************************************************************
host1                      : ok=16   changed=3    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

**Comment by ndtroubleshoot** [comment]
I investigated the firewald service and found the error in status:

Dec 03 15:00:55 hostname firewalld[1433]: ERROR: INVALID_INTERFACE

If stop and restart the firewalld service or reboot the server firewalld reports running without error.  It is only after running the Euca 5 FastStart script that firewalld status reports the ERROR: INVALID_INTERFACE so I suspect there is an error in the faststart script.

Example Output of the Error state of firewalld: systemctl status firewalld

firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-12-03 14:56:41 EST; 5min ago
     Docs: man:firewalld(1)
 Main PID: 1433 (firewalld)
   CGroup: /system.slice/firewalld.service
           └─1433 /usr/bin/python2 -Es /usr/sbin/firewalld --nofork --nopid

Dec 03 14:56:40 [hostname] systemd[1]: Starting firewalld - dynamic firewall daemon...
Dec 03 14:56:41 [hostname] systemd[1]: Started firewalld - dynamic firewall daemon.
Dec 03 14:56:41 [hostname] firewalld[1433]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release. Please consider disabling it now.
Dec 03 15:00:55 hostname firewalld[1433]: ERROR: INVALID_INTERFACE

**Comment by sjones4** [comment]
Once faststart has been attempted, you should be able to run it again with manual changes using:

```
# ansible-playbook -i /root/faststart_inventory.yml /usr/share/eucalyptus-ansible/playbook_vpcmido.yml
```

The faststart script generates the ansible inventory `/root/faststart_inventory.yml`.

To disable firewalld (if testing on an internal host) you can edit the inventory `vars:` section and set 

```
cloud_firewalld_configure: no
```

if you want the firewall enabled then you can manually specify the interfaces to be used:

```
cloud_firewalld_public_interface: ???
cloud_firewalld_cluster_interface: Null
```

the `cloud_firewalld_public_interface` should be set to the main interface on the host.

I'm going to close this issue, feel free to open a [eucalyptus repository issue](https://github.com/Corymbia/eucalyptus/issues) for tracking.
